const MUSEUMS = [
  {
    id: "moma", name: "MoMA", fullName: "The Museum of Modern Art", dayId: "2026-08-24", dayPanel: "museum", accent: "#d05763", time: "około 3 godz.",
    intro: "Najmocniejsza kolekcja modernizmu podczas tej podróży. Budynek czytamy od ikon z piętra 5 w dół ku sztuce współczesnej i wystawom czasowym.",
    statusNote: "MoMA często zmienia zestawienia sal. Status i numer galerii zapisujemy jako migawkę, a rano 24.08 potwierdzamy je w oficjalnej kolekcji.",
    floors: [
      { level: "6", title: "Wystawy czasowe", scale: 58, rooms: "duże galerie zmienne", text: "Program wystaw czasowych. Wchodzimy tylko wtedy, gdy temat jest ważniejszy niż kolekcja stała." },
      { level: "5", title: "1880–1940", scale: 92, rooms: "galerie 500", text: "Van Gogh, Cézanne, Matisse, Picasso, Monet, Dalí i narodziny modernizmu. Główne piętro Gosi." },
      { level: "4", title: "1940–1970", scale: 88, rooms: "galerie 400", text: "Pollock, Rothko, pop-art, minimalizm, fotografia, design i powojenna zmiana języka sztuki." },
      { level: "3", title: "Wystawy i design", scale: 72, rooms: "3 East / 3 West", text: "W sierpniu 2026 przede wszystkim Frida i Diego oraz wybrane galerie architektury, fotografii i designu." },
      { level: "2", title: "1970–dzisiaj", scale: 84, rooms: "galerie 200", text: "Sztuka współczesna zestawiana tematycznie; częste zmiany ekspozycji." },
      { level: "T2/T1", title: "Film i animacja", scale: 54, rooms: "poziomy podziemne", text: "Wystawa „It’s Alive!” i przestrzenie filmu. Moduł szczególnie dobry dla Matyldy." }
    ],
    works: [
      { id:"moma-starry", artist:"Vincent van Gogh", title:"Gwiaździsta noc", year:"1889", floor:"5", section:"malarstwo", priority:"must", status:"on", why:"Jeden z najważniejszych obrazów całej podróży: pejzaż zamieniony w zapis ruchu, pamięci i emocji.", look:"Najpierw zobacz rytm wirów z kilku metrów, potem podejdź do krótkich, gęstych pociągnięć farby." },
      { id:"moma-olives", artist:"Vincent van Gogh", title:"Drzewa oliwne", year:"1889", floor:"5", section:"malarstwo", priority:"good", status:"check", why:"Powstały w tym samym okresie w Saint-Rémy co „Gwiaździsta noc” i pozwalają porównać dwa sposoby budowania ruchu w naturze.", look:"Śledź kontury drzew i falujące pasma ziemi — niemal nic nie pozostaje nieruchome." },
      { id:"moma-demoiselles", artist:"Pablo Picasso", title:"Panny z Awinionu", year:"1907", floor:"5", section:"malarstwo", priority:"must", status:"on", why:"Obraz przełomowy dla kubizmu, ale również dzieło wymagające rozmowy o spojrzeniu na kobiety i zapożyczeniach ze sztuki afrykańskiej.", look:"Spróbuj ustalić, z ilu różnych punktów widzenia oglądasz jednocześnie twarze i ciała." },
      { id:"moma-musicians", artist:"Pablo Picasso", title:"Trzej muzykanci", year:"1921", floor:"5", section:"malarstwo", priority:"good", status:"check", why:"Kubizm staje się tu niemal teatralną układanką z kolorowych płaszczyzn.", look:"Znajdź granice trzech postaci i sprawdź, gdzie instrument, dłonie i ubrania zlewają się z tłem." },
      { id:"moma-mirror", artist:"Pablo Picasso", title:"Dziewczyna przed lustrem", year:"1932", floor:"5", section:"malarstwo", priority:"good", status:"check", why:"Portret Marie-Thérèse Walter zestawia ciało widziane bezpośrednio z jego ciemniejszym, niepokojącym odbiciem.", look:"Porównaj kolory twarzy i brzucha po obu stronach lustra." },
      { id:"moma-picasso-horse", artist:"Pablo Picasso", title:"Chłopiec prowadzący konia", year:"1905–06", floor:"5", section:"malarstwo", priority:"must", status:"on", why:"Monumentalna, niemal klasyczna postać pokazuje przejście Picassa od okresu różowego ku uproszczonej formie, która poprzedzi kubizm.", look:"Zauważ brak uzdy: gest dłoni i spokojny krok wystarczają, by połączyć chłopca z koniem." },
      { id:"moma-picasso-nudes", artist:"Pablo Picasso", title:"Dwa akty", year:"1906", floor:"5", section:"malarstwo", priority:"good", status:"check", why:"Ciężkie, uproszczone ciała pokazują, jak Picasso porzuca naturalizm i przygotowuje język dla „Panien z Awinionu”.", look:"Porównaj twarze przypominające maski z masywnym rytmem ramion, bioder i nóg." },
      { id:"moma-picasso-plaiting", artist:"Pablo Picasso", title:"Kobieta zaplatająca włosy", year:"1906", floor:"5", section:"malarstwo", priority:"good", status:"check", why:"Codzienny gest zostaje zamieniony w zwartą konstrukcję ciała; anatomia jest podporządkowana rytmowi brył.", look:"Prześledż zamknięty obieg ramion i włosów oraz sposób, w jaki postać niemal wypełnia całe płótno." },
      { id:"moma-waterlilies", artist:"Claude Monet", title:"Nenufary", year:"1914–26", floor:"5", section:"malarstwo", priority:"must", status:"on", why:"Monumentalny tryptyk działa bardziej jak otoczenie niż tradycyjny pejzaż w ramie.", look:"Podejdź bardzo blisko, aż zostaną tylko ślady pędzla, następnie cofnij się i pozwól wodzie złożyć się ponownie." },
      { id:"moma-dance", artist:"Henri Matisse", title:"Taniec (I)", year:"1909", floor:"5", section:"malarstwo", priority:"must", status:"on", why:"Pierwsza wersja kompozycji pokazuje, jak niewielka liczba linii i kolorów może stworzyć energię całej grupy.", look:"Obserwuj miejsca, w których dłonie prawie się łączą, i rytm przechylonych ciał." },
      { id:"moma-redstudio", artist:"Henri Matisse", title:"Czerwona pracownia", year:"1911", floor:"5", section:"malarstwo", priority:"good", status:"check", why:"Przestrzeń pracowni zostaje zalana czerwienią, a przedmioty utrzymują się dzięki cienkim konturom.", look:"Zobacz, które obrazy w obrazie zachowały własne kolory i dlaczego właśnie one." },
      { id:"moma-persistence", artist:"Salvador Dalí", title:"Trwałość pamięci", year:"1931", floor:"5", section:"malarstwo", priority:"must", status:"on", why:"Niewielki format zaskakuje po tysiącach wielkich reprodukcji. Miękkie zegary zmieniają precyzyjny pejzaż w sen o czasie.", look:"Porównaj twarde krawędzie skał i platformy z wiotkimi tarczami zegarów." },
      { id:"moma-broadway", artist:"Piet Mondrian", title:"Broadway Boogie Woogie", year:"1942–43", floor:"5", section:"malarstwo", priority:"must", status:"on", why:"Siatka Manhattanu, ruch uliczny i rytm boogie-woogie spotykają się w obrazie bez przedstawionych budynków.", look:"Szukaj pulsujących sekwencji żółtych, czerwonych i niebieskich pól zamiast jednego centrum." },
      { id:"moma-sleeping", artist:"Henri Rousseau", title:"Śpiąca Cyganka", year:"1897", floor:"5", section:"malarstwo", priority:"good", status:"check", why:"Niemożliwe spotkanie śpiącej postaci i lwa stało się ikoną poetyckiej, celowo nierealistycznej wyobraźni Rousseau.", look:"Zwróć uwagę, że lew nie atakuje — wącha postać w nieruchomej, księżycowej ciszy." },
      { id:"moma-object", artist:"Meret Oppenheim", title:"Obiekt", year:"1936", floor:"5", section:"rzeźba", priority:"good", status:"on", why:"Filiżanka, spodek i łyżeczka pokryte futrem łączą przyjemność dotyku z odrazą i niemożnością użycia.", look:"Wyobraź sobie sam moment picia — surrealizm uruchamia ciało, choć obiektu nie wolno dotknąć." },
      { id:"moma-brancusi", artist:"Constantin Brancusi", title:"Ptak w przestrzeni", year:"1928", floor:"5", section:"rzeźba", priority:"good", status:"check", why:"Brancusi nie rzeźbi piór ani skrzydeł; redukuje ptaka do idei pionowego lotu.", look:"Obejdź rzeźbę i zobacz, jak odbicie światła zmienia jej lekkość." },
      { id:"moma-pollock", artist:"Jackson Pollock", title:"One: Number 31, 1950", year:"1950", floor:"4", section:"malarstwo", priority:"must", status:"on", why:"Ogromne płótno rejestruje ruch całego ciała artysty pracującego nad obrazem rozłożonym na podłodze.", look:"Podejdź blisko, aby śledzić pojedynczą linię, potem odejdź i zobacz równowagę całej sieci." },
      { id:"moma-soup", artist:"Andy Warhol", title:"Puszki zupy Campbell", year:"1962", floor:"4", section:"malarstwo", priority:"must", status:"on", why:"Trzydzieści dwa podobne płótna przenoszą język supermarketu i masowej produkcji do muzeum.", look:"Sprawdź, które smaki i drobne elementy etykiet przełamują pozorną identyczność." },
      { id:"moma-kahlo", artist:"Frida Kahlo", title:"Autoportret z obciętymi włosami", year:"1940", floor:"3", section:"malarstwo", priority:"must", status:"on", why:"Kahlo buduje własny wizerunek po rozstaniu z Riverą poprzez garnitur, nożyczki i rozsypane włosy.", look:"Przeczytaj fragment nut i zobacz, jak włosy oplatają pustą przestrzeń niczym żywe linie." },
      { id:"moma-zapata", artist:"Diego Rivera", title:"Przywódca agrarny Zapata", year:"1931", floor:"3", section:"malarstwo", priority:"must", status:"on", why:"Rivera łączy prostą, czytelną kompozycję z polityczną opowieścią o ziemi, chłopach i rewolucji.", look:"Porównaj biały strój Zapaty i konia z ciemną grupą uzbrojonych chłopów." },
      { id:"moma-hope", artist:"Gustav Klimt", title:"Nadzieja II", year:"1907–08", floor:"5", section:"malarstwo", priority:"good", status:"check", why:"Ciąża, narodziny i śmierć pojawiają się jednocześnie w dekoracyjnej, złoconej powierzchni.", look:"Pod ornamentem sukni odnajdź trzy pochylone kobiece twarze." }
    ]
  },
  {
    id: "met", name: "The Met", fullName: "The Metropolitan Museum of Art", dayId: "2026-08-25", dayPanel: "museum", accent: "#8974a8", time: "3–4 godz.",
    intro: "Muzeum wielkości miasta. Moduł nie próbuje pokazać wszystkiego: porządkuje wybrane skrzydła, ale daje Gosi szeroki wybór arcydzieł i artystów.",
    statusNote: "Galerie The Met i pojedyncze obiekty bywają czasowo zamknięte. Numer galerii oraz status ekspozycji potwierdzamy rano w oficjalnym rekordzie dzieła.",
    floors: [
      { level:"2", title:"Malarstwo europejskie", scale:96, rooms:"skrzydła 600–900", text:"Największe zagęszczenie obrazów: od Duccia i Bronzina przez Velázqueza, Rembrandta i Vermeera po Moneta oraz van Gogha." },
      { level:"2", title:"American Wing", scale:78, rooms:"galerie 700", text:"Malarstwo amerykańskie, pokoje historyczne, meble i rzemiosło skupione wokół Engelhard Court." },
      { level:"1", title:"Egipt i Dendur", scale:88, rooms:"galerie 100–138", text:"Chronologiczna droga przez tysiące lat sztuki egipskiej kończąca się Świątynią Dendur." },
      { level:"1", title:"Rzeźba i sztuka dekoracyjna", scale:74, rooms:"Petrie Court i sąsiednie galerie", text:"Rzeźba europejska, Rodin, wnętrza i sztuka użytkowa." },
      { level:"G/1", title:"Costume Institute", scale:52, rooms:"galerie czasowe", text:"Ubiór jako konstrukcja, status i tożsamość. Dostęp zależy od bieżącej wystawy." }
    ],
    works: [
      { id:"met-dendur",artist:"Starożytny Egipt",title:"Świątynia Dendur",year:"ok. 15 p.n.e.",floor:"1",section:"Egipt",priority:"must",status:"on",why:"Cała świątynia została uratowana przed wodami Jeziora Nasera i przeniesiona do Nowego Jorku.",look:"Sprawdź reliefy cesarza Augusta przedstawionego jak faraon oraz graffiti pozostawione przez późniejszych podróżnych." },
      { id:"met-hatshepsut",artist:"Starożytny Egipt",title:"Posąg Hatszepsut",year:"ok. 1479–1458 p.n.e.",floor:"1",section:"Egipt",priority:"good",status:"check",why:"Kobieta-faraon korzysta z tradycyjnych znaków królewskiej władzy, również z konwencjonalnie męskiego ciała.",look:"Porównaj delikatne rysy twarzy z masywną, frontalną pozycją władcy." },
      { id:"met-washington",artist:"Emanuel Leutze",title:"Waszyngton przeprawiający się przez Delaware",year:"1851",floor:"2",section:"American Wing",priority:"must",status:"on",why:"Monumentalny obraz stworzył mit założycielski bardziej niż wierną rekonstrukcję wydarzenia.",look:"Policz typy postaci w łodzi i zobacz, jak światło buduje rolę Waszyngtona." },
      { id:"met-madamex",artist:"John Singer Sargent",title:"Madame X",year:"1883–84",floor:"2",section:"American Wing",priority:"must",status:"on",why:"Portret Virginie Gautreau wywołał skandal w Paryżu, a Sargent później przemalował położenie ramiączka.",look:"Zobacz napięcie między bladą skórą, czernią sukni i wykręconym profilem." },
      { id:"met-gulf",artist:"Winslow Homer",title:"Prąd Zatokowy",year:"1899",floor:"2",section:"American Wing",priority:"good",status:"check",why:"Samotny człowiek na uszkodzonej łodzi otoczony jest rekinami i odległą możliwością ratunku.",look:"Znajdź statek na horyzoncie i zdecyduj, czy daje nadzieję, czy zwiększa dramat." },
      { id:"met-cassatt",artist:"Mary Cassatt",title:"Młoda matka szyjąca",year:"1900",floor:"2",section:"malarstwo",priority:"good",status:"check",why:"Cassatt pokazuje codzienną bliskość bez sentymentalnego teatralizowania sceny.",look:"Zobacz, jak dziecko patrzy bezpośrednio na widza, podczas gdy matka pozostaje skupiona na pracy." },
      { id:"met-vermeer",artist:"Johannes Vermeer",title:"Młoda kobieta z dzbanem",year:"ok. 1662",floor:"2",section:"malarstwo europejskie",priority:"must",status:"on",why:"Światło, gest i kilka przedmiotów zamieniają zwykły poranek w precyzyjnie wyważony świat.",look:"Prześledź światło od okna przez nakrycie głowy, rękaw i metalową misę." },
      { id:"met-vermeer-lute",artist:"Johannes Vermeer",title:"Młoda kobieta z lutnią",year:"ok. 1662–63",floor:"2",section:"malarstwo europejskie",priority:"must",status:"on",why:"Strojenie lutni staje się cichą sceną oczekiwania; mapa i instrument sugerują świat poza zamkniętym pokojem.",look:"Zobacz, jak światło z okna prowadzi od pereł i twarzy ku dłoniom oraz instrumentowi." },
      { id:"met-vermeer-maid",artist:"Johannes Vermeer",title:"Śpiąca służąca",year:"ok. 1656–57",floor:"2",section:"malarstwo europejskie",priority:"must",status:"on",why:"Wczesny Vermeer buduje niejednoznaczną opowieść z gestu, kieliszka i pustej przestrzeni po usuniętej postaci.",look:"Przyjrzyj się otwartym drzwiom i zmianom kompozycji widocznym w badaniach obrazu — scena mogła opowiadać inną historię." },
      { id:"met-rembrandt",artist:"Rembrandt",title:"Arystoteles z popiersiem Homera",year:"1653",floor:"2",section:"malarstwo europejskie",priority:"must",status:"on",why:"Filozof dotyka popiersia Homera, a złoty łańcuch przypomina o napięciu między sławą, pieniędzmi i mądrością.",look:"Najważniejszy jest dotyk dłoni oraz światło wydobywające twarz i złoto z ciemności." },
      { id:"met-juan",artist:"Diego Velázquez",title:"Juan de Pareja",year:"1650",floor:"2",section:"malarstwo europejskie",priority:"must",status:"on",why:"Portret asystenta Velázqueza, który był wówczas przez niego zniewolony, łączy niezwykłą obecność modela z trudną historią ich relacji.",look:"Stań na wprost i zobacz, jak spojrzenie oraz sylwetka budują godność bez dodatkowych rekwizytów." },
      { id:"met-caravaggio",artist:"Caravaggio",title:"Zaparcie się świętego Piotra",year:"1610",floor:"2",section:"malarstwo europejskie",priority:"good",status:"check",why:"Ostatnie lata Caravaggia przynoszą ciemny, skupiony dramat rozgrywany gestami dłoni i twarzy.",look:"Policz palce oskarżycielki, żołnierza i Piotra — gesty prowadzą narrację zaparcia się trzy razy." },
      { id:"met-toledo",artist:"El Greco",title:"Widok Toledo",year:"ok. 1599–1600",floor:"2",section:"malarstwo europejskie",priority:"must",status:"on",why:"Jeden z pierwszych wielkich samodzielnych pejzaży zachodniej sztuki zmienia miasto w wizję burzy i duchowego napięcia.",look:"Porównaj zielone wzgórza z ciężkim niebem i sprawdź, czy topografia ma być dokładna." },
      { id:"met-bronzino",artist:"Agnolo Bronzino",title:"Portret młodego mężczyzny",year:"lata 1530.",floor:"2",section:"malarstwo europejskie",priority:"good",status:"check",why:"Chłodna elegancja i intelektualne rekwizyty tworzą wzorzec manierystycznego portretu dworskiego.",look:"Odnajdź groteskowe twarze ukryte w meblach i tkaninie." },
      { id:"met-duccio",artist:"Duccio di Buoninsegna",title:"Madonna z Dzieciątkiem",year:"ok. 1290–1300",floor:"2",section:"malarstwo europejskie",priority:"good",status:"check",why:"Mały obraz stoi na granicy bizantyjskiej tradycji i nowego zainteresowania czułością oraz przestrzenią.",look:"Zwróć uwagę na gest dziecka odsuwającego welon matki i parapet sugerujący głębię." },
      { id:"met-vangogh-cypresses",artist:"Vincent van Gogh",title:"Pole pszenicy z cyprysami",year:"1889",floor:"2",section:"malarstwo europejskie",priority:"must",status:"on",why:"Van Gogh zamienia trzy poziome pasy pejzażu w jeden rytm falujących form.",look:"Porównaj kształt cyprysu, chmur i gór — wszystkie zdają się podlegać temu samemu ruchowi." },
      { id:"met-vangogh-self",artist:"Vincent van Gogh",title:"Autoportret w słomkowym kapeluszu",year:"1887",floor:"2",section:"malarstwo europejskie",priority:"good",status:"check",why:"Krótki okres paryski pokazuje eksperyment z jasnym kolorem i kierunkowymi pociągnięciami pędzla.",look:"Tło, marynarka i twarz są zbudowane innym rytmem linii." },
      { id:"met-vangogh-irises",artist:"Vincent van Gogh",title:"Irysy",year:"1890",floor:"2",section:"malarstwo europejskie",priority:"good",status:"check",why:"Martwa natura powstała pod koniec życia artysty i zestawia dopełniające się żółcie oraz fiolety.",look:"Sprawdź, jak wazon i kwiaty niemal wypychają kompozycję poza krawędzie." },
      { id:"met-monet-bridge",artist:"Claude Monet",title:"Most nad stawem z nenufarami",year:"1899",floor:"2",section:"malarstwo europejskie",priority:"must",status:"on",why:"Ogród w Giverny był jednocześnie miejscem, projektem artysty i laboratorium obserwacji światła.",look:"Most tworzy prosty łuk, ale roślinność niemal całkowicie rozpuszcza konstrukcję." },
      { id:"met-monet-waterlilies",artist:"Claude Monet",title:"Nenufary",year:"1916–19",floor:"2",section:"malarstwo europejskie",priority:"must",status:"on",why:"Późny Monet usuwa horyzont i zamienia powierzchnię stawu w niemal abstrakcyjne pole światła, odbić i roślin.",look:"Najpierw podejdź blisko do swobodnych smug farby, potem cofnij się, aby ponownie zobaczyć wodę." },
      { id:"met-degas",artist:"Edgar Degas",title:"Lekcja tańca",year:"1874",floor:"2",section:"malarstwo europejskie",priority:"must",status:"on",why:"Degas pokazuje balet od strony prób, czekania i dyscypliny, nie efektownego spektaklu.",look:"Zobacz puste centrum i postacie ucięte krawędzią jak w przypadkowym kadrze fotograficznym." },
      { id:"met-renoir",artist:"Pierre-Auguste Renoir",title:"Madame Charpentier z dziećmi",year:"1878",floor:"2",section:"malarstwo europejskie",priority:"good",status:"check",why:"Portret rodzinny jest także popisem czerni, wzorów, wnętrza i pozycji społecznej.",look:"Jeden z „chłopców” w podpisach z epoki jest w rzeczywistości córką ubraną zgodnie z ówczesnym zwyczajem." },
      { id:"met-manet",artist:"Édouard Manet",title:"W łodzi",year:"1874",floor:"2",section:"malarstwo europejskie",priority:"good",status:"check",why:"Kadrowanie, szerokie powierzchnie koloru i niejednoznaczna relacja postaci pokazują nowoczesny wypoczynek.",look:"Horyzont znika, a żagiel i krawędź łodzi spłaszczają przestrzeń." },
      { id:"met-seurat",artist:"Georges Seurat",title:"Parada cyrkowa",year:"1887–88",floor:"2",section:"malarstwo europejskie",priority:"good",status:"check",why:"Nocne światło gazowe i rygorystyczny rytm punktów tworzą jednocześnie widowisko i dystans.",look:"Zobacz, jak poziome linie dzielą publiczność, muzyków i artystę." },
      { id:"met-klimt",artist:"Gustav Klimt",title:"Mäda Primavesi",year:"1912–13",floor:"2",section:"malarstwo europejskie",priority:"good",status:"check",why:"Portret dziewięcioletniej dziewczynki łączy silną osobowość modelki z dekoracyjnym, niemal abstrakcyjnym tłem.",look:"Zobacz zdecydowaną pozycję nóg i ręki, zupełnie inną od potulnego portretu dziecka." },
      { id:"met-rodin",artist:"Auguste Rodin",title:"Mieszczanie z Calais",year:"model 1884–95",floor:"1",section:"rzeźba",priority:"must",status:"on",why:"Pomnik bohaterstwa nie pokazuje triumfalnego wodza, lecz sześć różnych reakcji ludzi idących na możliwą śmierć.",look:"Obejdź grupę i wybierz postać, której gest najlepiej wyraża strach lub determinację." },
      { id:"met-tiffany",artist:"Louis Comfort Tiffany",title:"Jesienny pejzaż",year:"1923–24",floor:"2",section:"American Wing",priority:"good",status:"check",why:"Witraż wykorzystuje kolor i fakturę samego szkła jak materiał malarski.",look:"Podejdź do różnych fragmentów i zobacz szkło pofałdowane, nakładane oraz opalizujące." }
    ]
  },
  {
    id:"guggenheim",name:"Guggenheim",fullName:"Solomon R. Guggenheim Museum",dayId:"2026-08-23",dayPanel:"guggenheim",accent:"#d37845",time:"23.08 · 10:30–12:30",
    intro:"W Guggenheimie sam budynek jest pierwszym dziełem. Kolekcję poznaje się po spirali i w bocznych galeriach, ale dostępność konkretnych prac szczególnie zależy od programu wystaw.",
    statusNote:"Na 23.08.2026 oficjalnie zapowiedziane są Guggenheim Pop: 1960 to Now, Modern European Currents oraz stała Thannhauser Collection. Pełna kolekcja fundacji obejmuje również prace niewystawiane i obiekty z innych oddziałów — dlatego większość konkretnych dzieł nadal ma status „sprawdź przed wizytą”.",
    floors:[
      {level:"6 → 2",title:"Spirala rotundy",scale:94,rooms:"ciągła rampa",text:"Sercem budynku jest jedna pochyła droga. Program rotundy po zakończeniu wystawy Carol Bove 2 sierpnia wymaga potwierdzenia bliżej wizyty."},
      {level:"T4/5/7",title:"Guggenheim Pop: 1960 to Now",scale:74,rooms:"Tower Galleries",text:"Od Warhola, Lichtensteina i Kusamy po współczesne rozwinięcia języka reklamy, konsumpcji i masowych obrazów. Wystawa trwa do 10 stycznia 2027."},
      {level:"T2/4",title:"Modern European Currents",scale:58,rooms:"Tower Galleries",text:"Europejska awangarda początku XX wieku: intensywny kolor, duchowość, natura i droga ku abstrakcji. Wystawa trwa do 10 stycznia 2027."},
      {level:"2",title:"Thannhauser Collection",scale:62,rooms:"stałe galerie kolekcji",text:"Impresjoniści, postimpresjoniści i modernizm francuski — m.in. Manet, Van Gogh, Cézanne i Picasso. Konkretne obrazy mogą rotować."},
      {level:"1",title:"Rotunda i wejście",scale:55,rooms:"otwarta przestrzeń",text:"Najlepsze miejsce, aby zrozumieć spiralę, świetlik i relacje między poziomami."}
    ],
    works:[
      {id:"gugg-comp8",artist:"Vasily Kandinsky",title:"Kompozycja 8",year:"1923",floor:"sprawdź",section:"malarstwo",priority:"must",status:"check",why:"Geometria, kolor i rytm tworzą wizualny odpowiednik złożonej kompozycji muzycznej.",look:"Szukaj relacji między wielkim kołem, przekątnymi i małymi elementami zamiast jednego tematu."},
      {id:"gugg-circles",artist:"Vasily Kandinsky",title:"Kilka kół",year:"1926",floor:"sprawdź",section:"malarstwo",priority:"must",status:"check",why:"Koła unoszą się w ciemnej, niemal kosmicznej przestrzeni i pokazują emocjonalne działanie czystych form.",look:"Znajdź przezroczyste nakładanie się kół oraz największy czarny krąg z kolorową obwódką."},
      {id:"gugg-curve",artist:"Vasily Kandinsky",title:"Dominant Curve",year:"1936",floor:"sprawdź",section:"malarstwo",priority:"good",status:"check",why:"Późny Kandinsky łączy geometrię z formami przypominającymi organizmy obserwowane pod mikroskopem.",look:"Śledź wielką krzywą i zobacz, jak porządkuje drobne, swobodne elementy."},
      {id:"gugg-yellowcow",artist:"Franz Marc",title:"Żółta krowa",year:"1911",floor:"sprawdź",section:"malarstwo",priority:"must",status:"on",why:"Marc używa koloru symbolicznie, a wygięte ciało zwierzęcia wpisuje w rytm krajobrazu.",look:"Zobacz, jak kształt krowy powtarza linie wzgórz i dlaczego żółć nie próbuje być realistyczna."},
      {id:"gugg-ironing",artist:"Pablo Picasso",title:"Kobieta prasująca",year:"1904",floor:"sprawdź",section:"Thannhauser",priority:"must",status:"check",why:"Błękitny okres Picassa pokazuje fizyczny ciężar pracy bez dekoracyjnej atrakcyjności.",look:"Poczuj napięcie długich ramion i pochylonego ciała opartego na stole."},
      {id:"gugg-chagall-paris",artist:"Marc Chagall",title:"Paryż przez okno",year:"1913",floor:"sprawdź",section:"malarstwo",priority:"must",status:"check",why:"Nowoczesne miasto, wspomnienie rodzinnej Rosji i logika snu współistnieją bez potrzeby realistycznej narracji.",look:"Znajdź dwutwarzową postać, odwrócony pociąg i kota o ludzkiej twarzy."},
      {id:"gugg-greenviolin",artist:"Marc Chagall",title:"Zielony skrzypek",year:"1923–24",floor:"sprawdź",section:"malarstwo",priority:"must",status:"check",why:"Muzyk góruje nad miasteczkiem jako postać łącząca wspólnotę, tradycję i wyobraźnię.",look:"Zobacz, jak ogromne buty opierają się na dachach, a geometria wsi spotyka się z ruchem ciała."},
      {id:"gugg-malevich",artist:"Kazimir Malevich",title:"Poranek na wsi po śnieżycy",year:"1912–13",floor:"sprawdź",section:"malarstwo",priority:"good",status:"check",why:"Figury i pejzaż zostają przetworzone w cylindryczne, rytmiczne bryły zapowiadające abstrakcję.",look:"Spróbuj rozpoznać ludzi, ścieżki i domy, zanim zobaczysz tylko układ form."},
      {id:"gugg-manet",artist:"Édouard Manet",title:"Przed lustrem",year:"1876",floor:"sprawdź",section:"Thannhauser",priority:"good",status:"check",why:"Luźne pociągnięcia pędzla i prywatny moment toalety tworzą obraz nowoczesnego paryskiego życia.",look:"Lustro nie daje jasnego odbicia twarzy — ważniejsze są plecy, gorset i migotliwa powierzchnia."},
      {id:"gugg-renoir",artist:"Pierre-Auguste Renoir",title:"Kobieta z papugą",year:"1871",floor:"sprawdź",section:"Thannhauser",priority:"good",status:"on",why:"Wczesny Renoir łączy portret, modę i egzotyczny rekwizyt świadczący o statusie.",look:"Porównaj fakturę czarnej sukni, kwiatów i piór ptaka."},
      {id:"gugg-vangogh",artist:"Vincent van Gogh",title:"Góry w Saint-Rémy",year:"1889",floor:"sprawdź",section:"Thannhauser",priority:"must",status:"check",why:"Ten sam pobyt, podczas którego powstała „Gwiaździsta noc”, przyniósł pejzaż zbudowany z potężnych, pofałdowanych mas.",look:"Porównaj rytm gór z obrazem w MoMA i zobacz, jak niebo pozostaje tu stosunkowo spokojne."},
      {id:"gugg-monet",artist:"Claude Monet",title:"Palazzo Ducale widziane z San Giorgio Maggiore",year:"1908",floor:"sprawdź",section:"Thannhauser",priority:"good",status:"check",why:"Wenecja jest pretekstem do badania mgły, odbicia i rozpadu architektury w kolorze.",look:"Z daleka rozpoznaj pałac, z bliska sprawdź, jak mało precyzyjnych krawędzi naprawdę istnieje."},
      {id:"gugg-klee",artist:"Paul Klee",title:"Czerwony balon",year:"1922",floor:"sprawdź",section:"malarstwo",priority:"good",status:"check",why:"Mały obraz tworzy poetyckie miasto z prostych, półprzezroczystych pól i jednego intensywnego koła.",look:"Zobacz, jak czerwony punkt organizuje całą delikatną architekturę."},
      {id:"gugg-brancusi",artist:"Constantin Brancusi",title:"Adam i Ewa",year:"1921",floor:"sprawdź",section:"rzeźba",priority:"good",status:"check",why:"Dwie uproszczone formy ustawione jedna na drugiej łączą figurę, totem i równowagę materiałów.",look:"Obejdź obiekt i sprawdź, jak zmienia się relacja drewnianej oraz kamiennej części."},
      {id:"gugg-modigliani",artist:"Amedeo Modigliani",title:"Akt",year:"1917",floor:"sprawdź",section:"Thannhauser",priority:"good",status:"check",why:"Wydłużone ciało i bezpośrednie spojrzenie należą do serii aktów, które w 1917 roku wywołały policyjną interwencję na wystawie.",look:"Porównaj miękki kontur ciała z płaskim, ciepłym tłem."}
      ,{id:"gugg-cezanne-arms",artist:"Paul Cézanne",title:"Mężczyzna ze skrzyżowanymi ramionami",year:"ok. 1899",floor:"2",section:"Thannhauser",priority:"must",status:"check",why:"Portret nie opowiada anegdoty o modelu; Cézanne buduje obecność człowieka ciężarem brył, koloru i powtarzających się skosów.",look:"Porównaj skrzyżowane ręce z układem fałd marynarki i zobacz, jak tło przechyla przestrzeń."}
      ,{id:"gugg-picasso-yellowhair",artist:"Pablo Picasso",title:"Kobieta z żółtymi włosami",year:"1931",floor:"2",section:"Thannhauser",priority:"must",status:"check",why:"Picasso zamienia śpiącą Marie-Thérèse Walter w układ miękkich, monumentalnych form i intensywnego koloru.",look:"Zobacz, jak profil, włosy i dłonie składają się z łuków, które bardziej opisują sen niż anatomię."}
      ,{id:"gugg-rousseau-football",artist:"Henri Rousseau",title:"Piłkarze",year:"1908",floor:"sprawdź",section:"Modern European Currents",priority:"good",status:"check",why:"Rousseau przedstawia nowoczesny sport w celowo płaskim, niemal teatralnym pejzażu, ignorując akademicką perspektywę.",look:"Porównaj podobne pozy zawodników i rytm pasiastych strojów z regularnymi drzewami."}
      ,{id:"gugg-gauguin-vanilla",artist:"Paul Gauguin",title:"W gaju waniliowym, człowiek i koń",year:"1891",floor:"2",section:"Thannhauser",priority:"good",status:"check",why:"Tahitański motyw łączy dekoracyjny kolor z kolonialnym spojrzeniem europejskiego artysty — piękno obrazu wymaga również krytycznego kontekstu.",look:"Zobacz płaskie pasy zieleni i czerwieni oraz sposób, w jaki postać niemal wtapia się w roślinność."}
      ,{id:"gugg-pissarro-hermitage",artist:"Camille Pissarro",title:"Erem w Pontoise",year:"1867",floor:"2",section:"Thannhauser",priority:"good",status:"check",why:"Wczesny Pissarro pokazuje drogę i zabudowania bez salonowego upiększenia, zapowiadając bezpośrednią obserwację impresjonistów.",look:"Śledź drogę prowadzącą w głąb oraz drobne różnice zieleni budujące światło i pogodę."}
      ,{id:"gugg-braque-antwerp",artist:"Georges Braque",title:"Krajobraz w pobliżu Antwerpii",year:"1906",floor:"sprawdź",section:"Modern European Currents",priority:"good",status:"check",why:"Przed kubizmem Braque eksperymentował z fowistycznym kolorem, oddzielając barwę od dosłownego wyglądu natury.",look:"Sprawdź, gdzie intensywne pomarańcze i zielenie opisują światło, a gdzie zaczynają żyć samodzielnie."}
      ,{id:"gugg-metzinger-fan",artist:"Jean Metzinger",title:"Kobieta z wachlarzem",year:"1912",floor:"sprawdź",section:"Modern European Currents",priority:"good",status:"check",why:"Kubistyczny portret rozbija postać i otoczenie na nakładające się punkty widzenia, lecz nadal zachowuje czytelne rekwizyty.",look:"Najpierw znajdź twarz i wachlarz, potem zobacz, jak kontury przechodzą w geometryczne tło."}
      ,{id:"gugg-gleizes-bridge",artist:"Albert Gleizes",title:"Most Brookliński",year:"1915",floor:"sprawdź",section:"Modern European Currents",priority:"must",status:"check",why:"Europejski kubizm spotyka symbol nowoczesnego Nowego Jorku; most staje się konstrukcją ruchu, energii i przecinających się płaszczyzn.",look:"Szukaj łuków, lin i fragmentów panoramy, zamiast oczekiwać jednego realistycznego widoku mostu."}
      ,{id:"gugg-ringgold-tarbeach",artist:"Faith Ringgold",title:"Woman on a Bridge #1 of 5: Tar Beach",year:"1988",floor:"magazyn",section:"sztuka współczesna",priority:"must",status:"off",why:"Story quilt łączy malarstwo, tkaninę i tekst w opowieść o ośmioletniej Cassie, która leci nad Harlemem i wyobraża sobie wolność bez ograniczeń rasy, płci oraz klasy.",look:"Przeczytaj obramowanie jak część obrazu i odnajdź George Washington Bridge jako realne miejsce oraz symbol możliwości."}
      ,{id:"gugg-canthelp",artist:"Sun Yuan & Peng Yu",title:"Can’t Help Myself",year:"2016",floor:"magazyn",section:"sztuka współczesna",priority:"good",status:"off",why:"Robot przemysłowy bez końca zgarniał czerwoną ciecz do wyznaczonego obszaru. Dzieło uruchamia pytania o kontrolę, pracę, granice, nadzór i bezsensowną powtarzalność.",look:"W materiałach wideo obserwuj zmianę skojarzeń: od wydajnej maszyny do uwięzionej istoty wykonującej niemożliwe zadanie."}
    ]
  },
  {
    id:"whitney",name:"Whitney",fullName:"Whitney Museum of American Art",dayId:"2026-08-27",dayPanel:"museum",accent:"#4f91b6",time:"90–120 min",
    intro:"Amerykańska sztuka XX i XXI wieku oglądana wraz z panoramą West Side. Ekspozycje zmieniają się częściej niż w MoMA i The Met, dlatego moduł mocno eksponuje status dostępności.",
    statusNote:"Nie zakładamy dostępności Whitney Biennial po 23.08. Kolekcję i piętra aktualizujemy na podstawie programu obowiązującego 27.08.",
    floors:[
      {level:"8",title:"Kolekcja / wystawa",scale:52,rooms:"jedna duża galeria + taras",text:"Najwyższe piętro wystawowe i pierwszy szeroki widok na miasto."},
      {level:"7",title:"Duża galeria",scale:74,rooms:"otwarty plan",text:"Elastyczna przestrzeń dla dużych prezentacji kolekcji lub wystaw czasowych."},
      {level:"6",title:"Galerie zmienne",scale:82,rooms:"kilka sekcji",text:"Wystawy czasowe; trasa zależy od programu sierpniowego."},
      {level:"5",title:"Największe piętro",scale:96,rooms:"galeria bez stałych kolumn",text:"Największa przestrzeń wystawowa, często rdzeń głównej prezentacji."},
      {level:"3",title:"Teatr, prace na papierze",scale:45,rooms:"mniejsze przestrzenie",text:"Program filmu, performance’u i kameralnych ekspozycji."}
    ],
    works:[
      {id:"whitney-early",artist:"Edward Hopper",title:"Early Sunday Morning",year:"1930",floor:"sprawdź",section:"malarstwo",priority:"must",status:"check",why:"Pusta fasada przy Seventh Avenue pokazuje miasto poprzez światło, rytm okien i nieobecność ludzi.",look:"Znajdź zakrzywiony cień znaku oraz nierówności, które przełamują pozorną geometrię."},
      {id:"whitney-railroad",artist:"Edward Hopper",title:"Railroad Sunset",year:"1929",floor:"sprawdź",section:"malarstwo",priority:"good",status:"check",why:"Hopper redukuje podróż do poziomych pasów torów, wzgórz i intensywnego zachodu słońca.",look:"Zobacz samotną wieżę sygnałową i zdecyduj, czy pejzaż jest spokojny, czy niepokojący."},
      {id:"whitney-interior",artist:"Edward Hopper",title:"New York Interior",year:"1921",floor:"sprawdź",section:"malarstwo",priority:"good",status:"check",why:"Widz obserwuje kobietę od tyłu w prywatnym wnętrzu, bez pewności, czy szyje, czy gra na instrumencie.",look:"Zwróć uwagę na teatralne kadrowanie oraz wzór tkaniny zajmujący pierwszy plan."},
      {id:"whitney-summerdays",artist:"Georgia O’Keeffe",title:"Summer Days",year:"1936",floor:"sprawdź",section:"malarstwo",priority:"must",status:"check",why:"Czaszka jelenia unosi się nad pustynnym krajobrazem, łącząc śmierć, przestrzeń i niemal surrealny sen.",look:"Porównaj nierealną skalę czaszki z maleńkim pejzażem daleko poniżej."},
      {id:"whitney-music",artist:"Georgia O’Keeffe",title:"Music, Pink and Blue No. 2",year:"1918",floor:"sprawdź",section:"malarstwo",priority:"good",status:"check",why:"Abstrakcja próbuje przełożyć rytm i emocję muzyki na falujące pasma koloru.",look:"Śledź ruch od ciemnego centrum ku jaśniejszym krawędziom."},
      {id:"whitney-white-calico",artist:"Georgia O’Keeffe",title:"The White Calico Flower",year:"1931",floor:"sprawdź",section:"malarstwo",priority:"must",status:"check",why:"Silne zbliżenie kwiatu usuwa zwykłą skalę i zmienia delikatny motyw w monumentalny krajobraz form.",look:"Podążaj za białymi fałdami ku ciemnemu centrum i sprawdź, kiedy przestajesz widzieć kwiat, a zaczynasz abstrakcję."},
      {id:"whitney-second-story",artist:"Edward Hopper",title:"Second Story Sunlight",year:"1960",floor:"sprawdź",section:"malarstwo",priority:"must",status:"check",why:"Jaskrawe słońce i geometryczna fasada nie usuwają charakterystycznego dla Hoppera poczucia dystansu między ludźmi.",look:"Porównaj postawy dwóch kobiet i duże płaszczyzny światła z ciemnymi otworami okien."},
      {id:"whitney-circus",artist:"Alexander Calder",title:"Calder’s Circus",year:"1926–31",floor:"sprawdź",section:"rzeźba",priority:"must",status:"check",why:"Miniaturowy cyrk z drutu, korka i tkanin był uruchamianym przez artystę performansem, nie tylko nieruchomą rzeźbą.",look:"Obejrzyj dokumentację ruchu — bez niej łatwo przeoczyć humor i pomysłowość mechanizmów."},
      {id:"whitney-bridge",artist:"Alexander Calder",title:"Brooklyn Bridge",year:"1943",floor:"sprawdź",section:"malarstwo",priority:"good",status:"check",why:"Calder przekłada konstrukcję mostu na żywe pola koloru i energię nowojorskiej infrastruktury.",look:"Zobacz, co pozostało z rozpoznawalnej architektury po uproszczeniu."},
      {id:"whitney-threeflags",artist:"Jasper Johns",title:"Three Flags",year:"1958",floor:"sprawdź",section:"malarstwo",priority:"must",status:"check",why:"Trzy coraz mniejsze płótna wystają w stronę widza, zmieniając znany symbol w fizyczny przedmiot.",look:"Podejdź z boku, aby zobaczyć rzeczywistą głębokość i warstwy obrazu."},
      {id:"whitney-door",artist:"Willem de Kooning",title:"Door to the River",year:"1960",floor:"sprawdź",section:"malarstwo",priority:"good",status:"check",why:"Kilka szerokich gestów tworzy jednocześnie abstrakcję i sugestię otwarcia prowadzącego ku pejzażowi.",look:"Zdecyduj, czy jasny prostokąt jest drzwiami, światłem, czy tylko śladem ruchu pędzla."},
      {id:"whitney-house",artist:"Stuart Davis",title:"House and Street",year:"1931",floor:"sprawdź",section:"malarstwo",priority:"good",status:"check",why:"Davis łączy obserwację miasta z rytmem znaków, geometrii i amerykańskiej kultury wizualnej.",look:"Szukaj fragmentów liter, szyldów i architektury zanim kompozycja stanie się czystym układem."},
      {id:"whitney-subway",artist:"George Tooker",title:"The Subway",year:"1950",floor:"sprawdź",section:"malarstwo",priority:"must",status:"check",why:"Labirynt przejść, powtarzalne postacie i chłodne światło zamieniają codzienną podróż w obraz alienacji.",look:"Śledź linie wzroku i korytarze, które nie prowadzą do wyraźnego wyjścia."},
      {id:"whitney-queerfish",artist:"Mabel Dwight",title:"Queer Fish",year:"1936",floor:"sprawdź",section:"grafika",priority:"good",status:"check",why:"Dwight wykorzystuje akwarium do satyrycznej obserwacji widzów, którzy sami stają się oglądanym widowiskiem.",look:"Porównaj ekspresje ludzi i ryb po dwóch stronach szyby."},
      {id:"whitney-war",artist:"Jacob Lawrence",title:"The War Series",year:"1946–47",floor:"sprawdź",section:"malarstwo",priority:"must",status:"check",why:"Czternaście paneli opiera się na doświadczeniach Lawrence’a w Straży Przybrzeżnej i opowiada wojnę poprzez pracę, oczekiwanie oraz powrót.",look:"Jeśli seria jest pokazana, czytaj ją jak sekwencję filmu: powracające kolory i kształty łączą osobne sceny."},
      {id:"whitney-motley",artist:"Archibald Motley",title:"Gettin’ Religion",year:"1948",floor:"sprawdź",section:"malarstwo",priority:"good",status:"check",why:"Nocna ulica w Bronzeville pulsuje kolorem, muzyką i karykaturalną energią, jednocześnie dokumentując życie czarnej dzielnicy Chicago.",look:"Prześledź sztuczne źródła światła i każdą z wielu małych historii postaci."}
    ]
  }
];
